import { Sample } from '@/components/Sample'
import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div className="container text-center">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="mb-4 mt-10 text-3xl font-bold underline">
        Welcome to <a href="https://nextjs.org">Next.js!</a>
      </h1>

      <p className="bg-yellow-100">
        Get started by editing <code className="">pages/index.tsx</code>
      </p>

      <div className="m-5">
        <Sample />
      </div>
    </div>
  )
}

export default Home
